### ISSUE TITLE
Coverage plots from reverse strand data

### ISSUE THREAD

**Issue by vanlammessa** [ivanek/Gviz#29] opened 2020-04-21 14:24 UTC
Hello,

I'm trying to get some coverage plots for data of the reverse strand. I have only wiggle files to produce these plots. Some of the files have very narrow reads cause I need to plot them for comparison. My problem is that for most of my data creating the plot works without problems. But for some of the libraries it doesn't give me a correct plot.

I attached a sample with two plots. On the first plot "BHI-" you can see the issue, while the second one "BHI+" got plotted correctly. 
![Rplot](https://user-images.githubusercontent.com/43047607/79874622-e1abb780-83e8-11ea-8a87-0518afd01ae6.png)

`dt <- DataTrack(range=range, name=name, strand = "-", chromosome=chromosome, type="hist", fill.histogram=color, fontsize = 12, cex.axis=1, 
                  collapse = FALSE, cex.title = 1, size = 5, window = -1, alpha.title = 1, alpha = 0.5)

plotTracks(tracks, from=from, to=to, background.title = "white", 
                   col.histogram="NA", col.frame="white", col.axis="black", col="black",
                   col.title="black", extend.right = 10, extend.left = 10, reverseStrand = TRUE)
`

I hope you can help me with this issue. 
Best regards,
Vanessa

**Comment by vanlammessa** [comment] 2020-04-21 17:02
Update: I fixed the issue for my plots by setting the ylim manually now. But automatically setting the limits doesn't work for my data.

**Comment by ivanek** [comment] 2020-04-21 22:34
Hi @vanlammessa,

I am sorry but I do not see what the problem is. 
I also noticed,that in the meantime you found the solution to it, so I am closing it.

If you think that there is indeed a bug, please reopen it.

Best
Robert

**Closed by ivanek** 2020-04-21 22:34 UTC
