### ISSUE TITLE
Modify BiomartGeneRegionTrack parameters

### ISSUE THREAD

**Issue by eggrandio** [ivanek/Gviz#53] opened 2021-08-31 00:16 UTC
Hello,

I am generating some gene tracks programmatically, and I want to modify some of the parameters from a track generated by BiomartGeneRegionTrack. Specifically, I would like to modify the color and the annotation for one Arabidopsis gene, because Biomart returns a long name for the gene symbol, "BETA-OHASE2". I would like to change it to "BOH2" if possible.
```
ensembl = useMart("plants_mart",host="plants.ensembl.org")
ensembl = useDataset("athaliana_eg_gene",mart=ensembl)
gene_track = BiomartGeneRegionTrack(genome = "TAIR10", chromosome = "chr5",
                                      transcriptAnnotation = "symbol",
                                      shape = "arrow",
                                      filters=list(ensembl_transcript_id="AT5G52570.1"),
                                      name = "Gene", biomart = ensembl,
                                      col.line = NULL, col= NULL, fill = "black", fontcolor.group= "black",
                                      cex.group = 1, fontface.group = 4)
```
This generates the track with this as symbol:
```
symbol(gene_track)
[1] "BETA-OHASE 2" "BETA-OHASE 2" "BETA-OHASE 2" "BETA-OHASE 2" "BETA-OHASE 2" "BETA-OHASE 2" "BETA-OHASE 2" "BETA-OHASE 2"
[9] "BETA-OHASE 2"
```
When I plot this track I get the long annotation:
```
plotTracks(gene_track,transcriptAnnotation = "symbol")
```
![image](https://user-images.githubusercontent.com/49569940/131423140-688c563f-1ce0-41ce-97f9-7ff18a80268d.png)
When I try to change the "symbol" on `gene_track` by:
```
symbol(gene_track) = "BOH2"
symbol(gene_track)
[1] "BOH2" "BOH2" "BOH2" "BOH2" "BOH2" "BOH2" "BOH2" "BOH2" "BOH2"
```
When I plot it, I still get the old long annotation, even though the "symbol" of `gene_track` has been successfully changed. It is interesting that the plot only takes the space for "BOH2", but the long name is still plotted:
[
![image](https://user-images.githubusercontent.com/49569940/131423055-61420935-a6a5-49dd-a7d4-5e4cfe2618d3.png)
](url)

I don't know where is this long annotation stored on the BiomartGeneRegionTrack object. Any ideas? 

Also, the second issue, although less important is that when I try to change the BiomartGeneRegionTrack colors, sometimes not all of them are changed. I have to resort to `collapseTranscripts = "meta"` to make them show black:
```plotTracks(gene_track,utr3="black",utr5="black",protein_coding="black")```
![image](https://user-images.githubusercontent.com/49569940/131424354-c64e7bad-6d77-4b1b-b625-94029c561de2.png)

But for another gene, it only works partially:
```
gene_track2 = BiomartGeneRegionTrack(genome = "TAIR10", chromosome = "chr4",
                                    transcriptAnnotation = "symbol",
                                    shape = "arrow",
                                    filters=list(ensembl_transcript_id="AT4G16780.1"),
                                    name = "Gene", biomart = ensembl,
                                    col.line = NULL, col= NULL, fill = "black", fontcolor.group= "black",
                                    cex.group = 1,
                                    fontface.group = 4)
```
`plotTracks(gene_track2)`
![image](https://user-images.githubusercontent.com/49569940/131424714-822b373d-be93-4f9b-9a1e-96076751d829.png)
`plotTracks(gene_track2,utr3="black",utr5="black",protein_coding="black")`
![image](https://user-images.githubusercontent.com/49569940/131424476-24d09120-2d2f-4537-b124-3735314a028d.png)

Even when this gene only has utr5 utr3 and protein_coding features:
```
feature(gene_track2)
[1] "utr5"           "protein_coding" "protein_coding" "protein_coding" "protein_coding" "utr3" 
```

**Comment by ivanek** [comment] 2021-08-31 09:13
Hi @eggrandio,

In the case of `BiomartGeneRegionTrack` you need to convert it to `GeneRegionTrack` to use the modified symbols:

```
gene_track <- as(gene_track, "GeneRegionTrack")
symbol(gene_track) <- "BOH2"
plotTracks(gene_track, transcriptAnnotation = "symbol")
```

The coloring issue I could not reproduce I got it correctly colored in black.

```
gene_track2 <- BiomartGeneRegionTrack(genome = "TAIR10", chromosome = "chr4",
                                     transcriptAnnotation = "symbol",
                                     shape = "arrow",
                                     filters=list(ensembl_transcript_id="AT4G16780.1"),
                                     name = "Gene", biomart = ensembl,
                                     col.line = NULL, col= NULL, 
                                     fill = "black", fontcolor.group= "black",
                                     utr3="black",utr5="black",protein_coding="black",
                                     cex.group = 1,
                                     fontface.group = 4)

plotTracks(gene_track2)
```

**Comment by eggrandio** [comment] 2021-08-31 18:17
Thanks for the quick reply! I was able to rename the gene.

I don't know what could be happening with the coloring. I have the same issue with several genes. I will use the `collapseTranscripts` option for now.

**Comment by ivanek** [comment] 2021-09-01 15:45
Interesting, I do not set `collapseTranscripts` and still get the black filled polygons.

**Comment by ivanek** [comment] 2022-01-05 21:34
No feedback, closing.

**Closed by ivanek** 2022-01-05 21:34 UTC
Labels: Need reproducible example
