### ISSUE TITLE
No go: UcscTrack() with start="chromStart"

### ISSUE THREAD

**Issue by rafalcode** [ivanek/Gviz#79] opened 2023-05-24 18:54 UTC
Getting the cpgIslandExt track from UcscTrack() has stopped working with following error:
```
Error in .new_IRanges_from_start_end(start, end) :
'start' and 'end' must be numeric vectors
```
It seems "chromStart" and "chromEnd" are no longer valid for IRanges? It needs to numerics now?
A command from the vignette will be enough to reproduce
```
cpgIslands <- UcscTrack(genome = "mm9", chromosome = "chrX",
                   track = "cpgIslandExt", from = from, to = to,
                   trackType = "AnnotationTrack",
                   start = "chromStart", end = "chromEnd",
                   id = "name", shape = "box", fill = "#006400",
                   name = "CpG Islands")
```

**Comment by rafalcode** [comment] 2023-05-24 18:56
Ooops sorry forgot to mention versions
```
R version 4.3.0 (2023-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 12 (bookworm)

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.21.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_IE.UTF-8       LC_NUMERIC=C               LC_TIME=en_IE.UTF-8        LC_COLLATE=en_IE.UTF-8     LC_MONETARY=en_IE.UTF-8    LC_MESSAGES=en_IE.UTF-8    LC_PAPER=en_IE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_IE.UTF-8 LC_IDENTIFICATION=C

time zone: Europe/Dublin
tzcode source: system (glibc)

attached base packages:
[1] grid      stats4    stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] Cairo_1.6-0          Gviz_1.44.0          GenomicRanges_1.52.0 GenomeInfoDb_1.36.0  IRanges_2.34.0       S4Vectors_0.38.1     BiocGenerics_0.46.0

loaded via a namespace (and not attached):
  [1] DBI_1.1.3                   bitops_1.0-7                deldir_1.0-9                gridExtra_2.3               biomaRt_2.56.0              rlang_1.1.1                 magrittr_2.0.3              biovizBase_1.48.0           matrixStats_0.63.0
 [10] compiler_4.3.0              RSQLite_2.3.1               GenomicFeatures_1.52.0      png_0.1-8                   vctrs_0.6.2                 ProtGenerics_1.32.0         stringr_1.5.0               pkgconfig_2.0.3             crayon_1.5.2
 [19] fastmap_1.1.1               backports_1.4.1             dbplyr_2.3.2                XVector_0.40.0              utf8_1.2.3                  Rsamtools_2.16.0            rmarkdown_2.21              bit_4.0.5                   xfun_0.39
 [28] zlibbioc_1.46.0             cachem_1.0.8                progress_1.2.2              blob_1.2.4                  DelayedArray_0.26.3         BiocParallel_1.34.2         jpeg_0.1-10                 parallel_4.3.0              prettyunits_1.1.1
 [37] cluster_2.1.4               VariantAnnotation_1.46.0    R6_2.5.1                    stringi_1.7.12              RColorBrewer_1.1-3          rtracklayer_1.60.0          rpart_4.1.19                Rcpp_1.0.10                 SummarizedExperiment_1.30.1
 [46] knitr_1.42                  base64enc_0.1-3             Matrix_1.5-4.1              nnet_7.3-19                 tidyselect_1.2.0            rstudioapi_0.14             dichromat_2.0-0.1           yaml_2.3.7                  codetools_0.2-19
 [55] curl_5.0.0                  lattice_0.21-8              tibble_3.2.1                Biobase_2.60.0              KEGGREST_1.40.0             evaluate_0.21               foreign_0.8-84              BiocFileCache_2.8.0         xml2_1.3.4
 [64] Biostrings_2.68.1           pillar_1.9.0                filelock_1.0.2              MatrixGenerics_1.12.0       checkmate_2.2.0             generics_0.1.3              RCurl_1.98-1.12             ensembldb_2.24.0            hms_1.1.3
 [73] ggplot2_3.4.2               munsell_0.5.0               scales_1.2.1                glue_1.6.2                  Hmisc_5.1-0                 lazyeval_0.2.2              tools_4.3.0                 interp_1.1-4                BiocIO_1.10.0
 [82] data.table_1.14.8           BSgenome_1.68.0             GenomicAlignments_1.36.0    XML_3.99-0.14               latticeExtra_0.6-30         AnnotationDbi_1.62.1        colorspace_2.1-0            GenomeInfoDbData_1.2.10     htmlTable_2.4.1
 [91] restfulr_0.0.15             Formula_1.2-5               cli_3.6.1                   rappdirs_0.3.3              fansi_1.0.4                 S4Arrays_1.0.4              dplyr_1.1.2                 AnnotationFilter_1.24.0     gtable_0.3.3
[100] digest_0.6.31               rjson_0.2.21                htmlwidgets_1.6.2           memoise_2.0.1               htmltools_0.5.5             lifecycle_1.0.3             httr_1.4.6                  bit64_4.0.5
```

**Comment by ivanek** [comment] 2023-05-25 07:58
Hi @rafalcode,

Interesting, it works for me. What do you store in `from` and `to` variables?

The code below works for me fine.

```
library(Gviz)

from <- 20e6
to <- 25e6
cpgIslands <- UcscTrack(genome = "mm9", chromosome = "chrX",
                        track = "cpgIslandExt", from = from, to = to,
                        trackType = "AnnotationTrack",
                        start = "chromStart", end = "chromEnd",
                        id = "name", shape = "box", fill = "#006400",
                        name = "CpG Islands")
```

**Comment by rafalcode** [comment] 2023-05-25 15:38
Hi @ivanek,
OK, yes, I hadn't defined `from` and `to`. That example does work for me now.
But not in my production code, though my call is almost identical.
Even still, with `from` and `to` undefined, the error text is not helpful as it talks about `start` and `end`, and yet it was the `from` and `to` that I got wrong. Still doing some tests ...

**Comment by ivanek** [comment] 2023-05-25 17:09
I am afraid, that without reproducible example I cannot help.

**Comment by rafalcode** [comment] 2023-05-26 09:33
Yes, I understand, sorry, I should have thanked you before .. this could easily be a problem outside of Gviz .. I'm trying again this weekend.

**Comment by ivanek** [comment] 2023-08-17 09:33
No feedback, closing.

**Closed as completed by ivanek** 2023-08-17 09:33 UTC
Labels: Need reproducible example
